//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearchConference
{


    public partial class AdminMemberManagement
    {
        protected global::System.Web.UI.WebControls.Button DeleteButton;
        protected global::System.Web.UI.WebControls.Button Search;
        protected global::System.Web.UI.WebControls.Button Insert;
        protected global::System.Web.UI.WebControls.Button Update;
        protected global::System.Web.UI.WebControls.GridView GV1;
        protected global::System.Web.UI.WebControls.Label lblmessage;
        protected global::System.Web.UI.WebControls.TextBox TxtMbrID;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAccountStatus;
        protected global::System.Web.UI.WebControls.TextBox txtAccount;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDispalyName;
        protected global::System.Web.UI.WebControls.TextBox TxtDisplayName;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divLoginId;
        protected global::System.Web.UI.WebControls.TextBox TxtUserName;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divpassword;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divSalt;
        protected global::System.Web.UI.WebControls.TextBox TxtSalt;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMaxRevw;
        protected global::System.Web.UI.WebControls.TextBox TxtMaxReview;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divRole;
        protected global::System.Web.UI.WebControls.DropDownList ddRole;










    }
}
